export interface ArticleSection {
    id: string;
    heading: string;
    paragraphs: string[];
    image?: string;
}

export type ArticleCategory =
    | "Property"
    | "Market"
    | "Investment"
    | "News"
    | "Market Analysis"
    | "Real Estate News"
    | "Guides"
    | "Home & Life"
    | "Project Reviews"
    | "Home Radar";

export interface Article {
    id: string;
    slug: string;
    title: string;
    excerpt: string;
    content?: string;
    sections?: ArticleSection[];
    category: ArticleCategory;
    image: string;
    author: string;
    date: string;
    readTime: string;
    featured?: boolean;
    isHero?: boolean;
}

export const articles: Article[] = [
    {
        id: "1",
        slug: "golden-horizon-sentosa-cove",
        title: "Golden Horizon Group Eyes Expansion into Sentosa Cove",
        excerpt:
            "The developer is looking to acquire prime waterfront lands in one of Singapore's most prestigious residential enclaves, signaling a bold move into the ultra-luxury segment.",
        category: "Property",
        image: "https://images.unsplash.com/photo-1524813686514-a57563d77965?w=1200&q=80",
        author: "Jia Li Tan",
        date: "October 25, 2026",
        readTime: "7 mins read",
        featured: true,
        sections: [
            {
                id: "volume-scarcity",
                heading: "Why Volume Matters More Than Scarcity Alone",
                paragraphs: [
                    "Despite ongoing economic uncertainty, residential property demand remained resilient in the first quarter of 2026. Industry analysts observed sustained interest in well-located homes, particularly in mature estates and city-fringe developments.",
                    "Buyers continue to prioritise long-term value, with accessibility, nearby amenities, and future infrastructure developments playing a key role in decision-making. Sellers, on the other hand, are adopting more realistic pricing strategies, leading to healthier transaction volumes compared to the previous quarter.",
                    "Experts note that while interest rates remain a consideration, confidence in the property market has not weakened significantly. Looking ahead, the market is expected to stay stable, with opportunities emerging for both homebuyers and investors who adopt a data-driven approach.",
                ],
            },
            {
                id: "price-engine",
                heading: "Liquidity as a Price Engine, Not a Risk Factor",
                paragraphs: [
                    "Even with the economy being a bit shaky, demand for homes held strong in the first quarter of 2026. Analysts noticed that people are still keen on buying well-located properties, especially in established neighbourhoods and city-edge developments.",
                    "Homebuyers are focusing on long-term value, considering things like accessibility, nearby amenities, and future infrastructure when making choices. Sellers are getting more realistic with their pricing, which is helping boost transaction numbers compared to last quarter.",
                    "Experts say that while interest rates are still a factor, overall confidence in the property market hasn't dropped much. Looking forward, the market seems set to stay stable, with chances popping up for both homebuyers and investors who use data to guide their decisions.",
                ],
                image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
            },
            {
                id: "terrace-homes",
                heading: "Terrace Homes: The Engine of District 19\u2019s Landed Market",
                paragraphs: [
                    "Despite the shaky economy, home demand stayed strong in early 2026. Analysts found that buyers are still eager to snag well-located properties, especially in established neighborhoods and developments near the city.",
                    "Homebuyers are all about long-term value, looking at things like accessibility, nearby amenities, and future infrastructure when making their choices. Sellers are getting more realistic with their prices, which is helping boost sales compared to last quarter.",
                    "Experts say that while interest rates are still a concern, overall confidence in the property market hasn't dipped much. Looking ahead, the market seems poised to remain stable, with opportunities popping up for both homebuyers and investors who rely on data to make their decisions.",
                ],
                image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
            },
            {
                id: "corner-terraces",
                heading: "Corner Terraces and Semi-Detached Homes: Selective Upside, Not Uniform Growth",
                paragraphs: [
                    "Corner terrace houses and semi-detached properties have shown mixed performance across different districts. While some pockets of the market recorded meaningful price gains, the appreciation has been selective rather than broad-based.",
                    "Buyers looking at these segments are advised to pay close attention to plot sizes, remaining lease tenure, and proximity to upcoming MRT stations. Properties that tick multiple boxes tend to command stronger premiums and attract faster sales.",
                    "The data suggests that while average prices have held steady, the spread between top-performing and underperforming properties within the same subtype has widened. Investors should take a granular approach when evaluating corner terraces and semi-detached homes for potential upside.",
                ],
            },
            {
                id: "detached-homes",
                heading: "Detached Homes: A Price, Infrastructure, Amenities, and the Durability of Demand",
                paragraphs: [
                    "Good Class Bungalows and detached homes remain the most aspirational segment of Singapore's residential market. Transaction volumes in this category are naturally lower, but each deal carries significant weight in terms of market sentiment.",
                    "Infrastructure improvements, particularly the expansion of the Thomson-East Coast Line and Cross Island Line, are reshaping accessibility in traditionally less-connected landed enclaves. Properties benefiting from these upgrades are seeing renewed buyer interest.",
                    "The durability of demand for detached homes is underpinned by a limited supply pipeline and the enduring preference among high-net-worth families for spacious, freehold properties. Barring a sharp economic downturn, this segment is expected to maintain its premium positioning throughout 2026.",
                ],
            },
        ],
    },
    {
        id: "2",
        slug: "capitacorp-training-real-estate",
        title: "CapitaCorp Advances Training for Next Real Estate Ventures",
        excerpt:
            "Singapore-based CapitaCorp has initiated talks with the Ministry of National Development to explore new urban development opportunities. The project is estimated to require an investment of $500 million, with funding sourced from a mix of private equity and government grants. CapitaCorp has indicated ongoing discussions with various financial institutions to secure the necessary capital.",
        category: "Market",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        author: "James Wong",
        date: "Feb 18, 2026",
        readTime: "4 min read",
    },
    {
        id: "3",
        slug: "singapore-property-market-2026",
        title: "Singapore Property Market Shows Resilience Amid Global Uncertainty",
        excerpt:
            "Despite headwinds from global markets, Singapore's property sector continues to demonstrate remarkable stability, with prices holding firm across most segments.",
        category: "Market",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        author: "Michael Tan",
        date: "Feb 17, 2026",
        readTime: "6 min read",
    },
    {
        id: "4",
        slug: "cbd-office-space-demand",
        title: "CBD Office Space Demand Surges as Tech Firms Expand",
        excerpt:
            "Technology companies are driving a new wave of demand for premium office spaces in Singapore's Central Business District, pushing rental yields to new highs.",
        category: "Investment",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        author: "David Lim",
        date: "Feb 15, 2026",
        readTime: "3 min read",
    },
    {
        id: "5",
        slug: "green-building-certifications",
        title: "Green Building Certifications: What Investors Need to Know",
        excerpt:
            "As sustainability becomes a key factor in property valuation, understanding green building certifications is essential for smart investment decisions.",
        category: "Investment",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        author: "Lisa Ng",
        date: "Feb 14, 2026",
        readTime: "7 min read",
    },
    {
        id: "6",
        slug: "hdb-resale-prices-trend",
        title: "HDB Resale Prices Continue Upward Trend in Q1 2026",
        excerpt:
            "Public housing resale transactions have seen another quarter of growth, with mature estates leading the price appreciation across the island.",
        category: "News",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        author: "Rachel Koh",
        date: "Feb 12, 2026",
        readTime: "4 min read",
    },
    {
        id: "7",
        slug: "property-management-trends",
        title: "Smart Property Management: AI and IoT Transform Building Operations",
        excerpt:
            "From predictive maintenance to energy optimization, intelligent building management systems are reshaping how properties are operated and maintained.",
        category: "Property",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
        author: "Kevin Chia",
        date: "Feb 10, 2026",
        readTime: "5 min read",
    },
    {
        id: "8",
        slug: "luxury-condo-market-outlook",
        title: "Luxury Condo Market: Foreign Buyers Return with Confidence",
        excerpt:
            "International buyers are re-entering Singapore's luxury condominium market in force, driven by attractive valuations and the city-state's stable regulatory environment.",
        category: "Property",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        author: "Amanda Lee",
        date: "Feb 8, 2026",
        readTime: "6 min read",
    },
    {
        id: "9",
        slug: "real-estate-scholarship",
        title: "Small REITs Eyeing Bigger Scholarships: What's Going On?",
        excerpt:
            "Smaller real estate investment trusts are making surprising moves in education sponsorship. Industry watchers explore the strategy behind this emerging trend.",
        category: "News",
        image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80",
        author: "Dennis Tan",
        date: "Feb 6, 2026",
        readTime: "4 min read",
    },
    {
        id: "10",
        slug: "property-market-data-analytics",
        title: "Data Analytics Reshaping Property Investment Decisions",
        excerpt:
            "Institutional investors are increasingly turning to big data and machine learning to identify undervalued properties and predict market movements.",
        category: "Investment",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        author: "Grace Ong",
        date: "Feb 4, 2026",
        readTime: "5 min read",
    },
    {
        id: "11",
        slug: "cta-luxury-residences-meyerroad",
        title: "CTA to Develop Luxury Residences in Meyer Road",
        excerpt:
            "CTA is planning a new luxury residential project on Meyer Road, combining modern architecture with coastal living in one of the most exclusive east-coast addresses.",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        author: "Jia Li Tan",
        date: "Feb 2, 2026",
        readTime: "5 min read",
    },
    {
        id: "12",
        slug: "hdb-eco-friendly-punggol",
        title: "HDB Unveils Plans for Eco-Friendly Housing in Punggol Northshore",
        excerpt:
            "HDB is set to introduce sustainable living concepts in Punggol Northshore with new eco-friendly housing developments featuring green corridors and energy-efficient designs.",
        category: "Home & Life",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        author: "Rachel Koh",
        date: "Jan 30, 2026",
        readTime: "4 min read",
    },
    {
        id: "13",
        slug: "capitaland-ascendas-logistics-jurong",
        title: "CapitaLand Ascendas REIT Acquires Logistics Hub in Jurong East",
        excerpt:
            "CapitaLand Ascendas REIT expands its portfolio with the acquisition of a state-of-the-art logistics hub in Jurong East, tapping into Singapore's growing e-commerce sector.",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&q=80",
        author: "David Lim",
        date: "Jan 28, 2026",
        readTime: "6 min read",
    },
    {
        id: "14",
        slug: "cdl-retail-spaces-bugis",
        title: "City Developments Limited Launches New Retail Spaces in Bugis",
        excerpt:
            "CDL is set to launch a fresh wave of retail spaces in the Bugis area, targeting experiential retail and artisan brands to reinvigorate one of Singapore's most vibrant districts.",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        author: "Amanda Lee",
        date: "Jan 26, 2026",
        readTime: "4 min read",
    },
    {
        id: "15",
        slug: "surbana-jurong-tampines",
        title: "Surbana Jurong to Lead Urban Development Projects in Tampines",
        excerpt:
            "Surbana Jurong has been appointed to oversee a series of urban development projects in the Tampines region, focusing on smart city infrastructure and community spaces.",
        category: "Project Reviews",
        image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        author: "Kevin Chia",
        date: "Jan 24, 2026",
        readTime: "5 min read",
    },
    {
        id: "16",
        slug: "frasers-office-one-north",
        title: "Frasers Property Reveals Innovative Office Spaces in One North",
        excerpt:
            "Frasers Property unveils plans for modern office spaces in One North designed to attract tech startups and established firms with flexible, community-oriented layouts.",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
        author: "Michael Tan",
        date: "Jan 22, 2026",
        readTime: "5 min read",
    },
    {
        id: "17",
        slug: "ascendas-singbridge-changi",
        title: "Ascendas Singbridge Announces New Mixed-Use Development in Changi",
        excerpt:
            "Ascendas Singbridge unveils a major mixed-use development in Changi that integrates retail, residential, and business spaces to create a vibrant live-work-play community.",
        category: "Project Reviews",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        author: "Dennis Tan",
        date: "Jan 20, 2026",
        readTime: "6 min read",
    },
    {
        id: "18",
        slug: "guocoland-smart-home-initiatives",
        title: "GuocoLand Launches Smart Home Initiatives in New District",
        excerpt:
            "GuocoLand introduces cutting-edge smart home technologies in its newest district development, offering residents seamless automation and IoT-enabled living.",
        category: "Home Radar",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        author: "Lisa Ng",
        date: "Jan 18, 2026",
        readTime: "4 min read",
    },
    {
        id: "19",
        slug: "mapletree-industrial-park",
        title: "Mapletree Investments Expands Portfolio with New Industrial Park",
        excerpt:
            "Mapletree Investments has announced plans for a new industrial park in Singapore's western corridor, targeting advanced manufacturing and biotech tenants.",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        author: "James Wong",
        date: "Jan 16, 2026",
        readTime: "5 min read",
    },
    {
        id: "20",
        slug: "oxley-commercial-novena",
        title: "Oxley Holdings Debuts New Landmark Commercial Development in Novena",
        excerpt:
            "Oxley Holdings introduces a landmark mixed-use commercial development in Novena, featuring state-of-the-art office towers and retail-dining destinations.",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1464938050520-ef2571e0d6e0?w=800&q=80",
        author: "Grace Ong",
        date: "Jan 14, 2026",
        readTime: "7 min read",
    },
    {
        id: "21",
        slug: "surbana-green-infrastructure",
        title: "Surbana Jurong Partners with Government on Green Infrastructure Initiatives",
        excerpt:
            "Surbana Jurong is working closely with the government to enhance urban resilience through green infrastructure projects, including managed waterways and vertical forests.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        author: "Kevin Chia",
        date: "Jan 12, 2026",
        readTime: "6 min read",
    },
    {
        id: "22",
        slug: "keppel-waterfront-residential",
        title: "Keppel Land Announces New Waterfront Residential Project in Nanyang",
        excerpt:
            "Keppel Land is set to develop a premium waterfront residential project in Nanyang, promising world-class amenities and breathtaking views of the southern coastline.",
        category: "Project Reviews",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        author: "Jia Li Tan",
        date: "Jan 10, 2026",
        readTime: "5 min read",
    },
    {
        id: "23",
        slug: "first-time-buyer-guide-2026",
        title: "First-Time Buyer's Guide to Navigating Singapore's Property Market in 2026",
        excerpt:
            "A comprehensive step-by-step guide for first-time homebuyers on how to approach Singapore's property market, from budgeting and loan eligibility to choosing the right neighbourhood.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
        author: "Rachel Koh",
        date: "Jan 8, 2026",
        readTime: "8 min read",
    },
    {
        id: "24",
        slug: "minimalist-living-hdb",
        title: "Minimalist Living: How to Transform Your HDB Flat Into a Modern Sanctuary",
        excerpt:
            "Interior design experts share practical tips for embracing minimalist living in compact HDB flats, maximising space with clean lines, neutral tones, and smart storage.",
        category: "Home Radar",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
        author: "Amanda Lee",
        date: "Jan 6, 2026",
        readTime: "5 min read",
    },
    {
        id: "25",
        slug: "biophilic-design-condos",
        title: "Biophilic Design Trends Reshaping Singapore's New Condominiums",
        excerpt:
            "Developers are increasingly incorporating biophilic design — natural light, greenery, and organic materials — into new condo projects, blurring the line between indoors and outdoors.",
        category: "Home Radar",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        author: "Lisa Ng",
        date: "Jan 4, 2026",
        readTime: "5 min read",
    },
    {
        id: "26",
        slug: "housing-loan-interest-rates",
        title: "Understanding Housing Loan Interest Rates: Fixed vs Floating in 2026",
        excerpt:
            "With interest rates in flux, homebuyers face a critical choice between fixed and floating rate packages. We break down the pros, cons, and what experts recommend.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        author: "Michael Tan",
        date: "Jan 2, 2026",
        readTime: "7 min read",
    },
    {
        id: "27",
        slug: "singapore-landed-market-2026",
        title: "Singapore's Landed Property Market: Key Trends to Watch in 2026",
        excerpt:
            "An in-depth analysis of Singapore's landed property market covering price movements, demand patterns, and emerging hotspots for terrace, semi-detached, and bungalow homes.",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        author: "David Lim",
        date: "Dec 28, 2025",
        readTime: "8 min read",
    },
    {
        id: "28",
        slug: "community-living-tengah",
        title: "Community Living Redefined: Inside Tengah's Eco-Town Blueprint",
        excerpt:
            "Singapore's first car-free town centre in Tengah promises a new model of community living with integrated green features, shared spaces, and pedestrian-friendly design.",
        category: "Home & Life",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        author: "Dennis Tan",
        date: "Dec 26, 2025",
        readTime: "6 min read",
    },
    {
        id: "29",
        slug: "cbd-office-rents-hit-record",
        title: "CDL to Develop Luxury Residences in Meyer Road",
        excerpt:
            "CDL is planning a new luxury residential project at Meyer Road, capitalizing on the high-end property ma...",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        author: "David Lim",
        date: "Dec 24, 2025",
        readTime: "3 mins read",
    },
    {
        id: "30",
        slug: "hdb-eco-punggol-plans",
        title: "HDB Unveils Plans for Eco-Friendly Housing in Punggol Northshore",
        excerpt:
            "HDB is set to introduce sustainable living concepts in Punggol Northshore with new eco-friendly housing pr...",
        category: "Market Analysis",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        author: "Rachel Koh",
        date: "Dec 22, 2025",
        readTime: "3 mins read",
    },
    {
        id: "31",
        slug: "capitaland-ascendas-jurong-logistics",
        title: "CapitaLand Ascendas REIT Acquires Logistics Hub in Jurong East",
        excerpt:
            "CapitaLand Ascendas REIT expands its portfolio with the acquisition of a prime logistics hub in Jurong East.",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        author: "Michael Tan",
        date: "Dec 20, 2025",
        readTime: "3 mins read",
    },
    {
        id: "32",
        slug: "cdl-retail-bugis-expansion",
        title: "City Developments Limited Launches New Retail Space in Bugis",
        excerpt:
            "City Developments Limited announces the opening of a vibrant new retail space aimed at enhancing the sh...",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        author: "Amanda Lee",
        date: "Dec 18, 2025",
        readTime: "4 mins read",
    },
    {
        id: "33",
        slug: "surbana-jurong-tengah-urban",
        title: "Surbana Jurong to Lead Urban Development Projects in Tengah",
        excerpt:
            "Surbana Jurong has been appointed to oversee multiple urban development projects in the Tengah ar...",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        author: "Kevin Chia",
        date: "Dec 16, 2025",
        readTime: "5 mins read",
    },
    {
        id: "34",
        slug: "frasers-one-north-office",
        title: "Frasers Property Reveals Innovative Office Spaces in One North",
        excerpt:
            "Frasers Property unveils plans for modern office spaces designed to foster collaboration and creativity in One...",
        category: "Real Estate News",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
        author: "James Wong",
        date: "Dec 14, 2025",
        readTime: "3 mins read",
    },
    {
        id: "35",
        slug: "renovation-permit-guide",
        title: "Complete Guide to Renovation Permits and HDB Approval Process",
        excerpt:
            "Everything homeowners need to know about obtaining renovation permits, HDB guidelines, and working with licensed contractors.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        author: "Lisa Ng",
        date: "Dec 12, 2025",
        readTime: "5 mins read",
    },
    {
        id: "36",
        slug: "cpf-housing-withdrawal-guide",
        title: "CPF Housing Withdrawal: How Much Can You Use for Your Property?",
        excerpt:
            "A detailed breakdown of CPF Ordinary Account usage for property purchases, including limits, rules, and accrued interest implications.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        author: "Michael Tan",
        date: "Dec 10, 2025",
        readTime: "6 mins read",
    },
    {
        id: "37",
        slug: "property-tax-singapore-guide",
        title: "Understanding Property Tax in Singapore: Rates, Rebates, and Appeals",
        excerpt:
            "Navigate Singapore's property tax system with this comprehensive guide covering annual value assessments, tax rates, and how to file an appeal.",
        category: "Guides",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        author: "Grace Ong",
        date: "Dec 8, 2025",
        readTime: "7 mins read",
    },
];

export interface TrendingTopic {
    id: string;
    label: string;
    image: string;
    slug: string;
}

export const trendingTopics: TrendingTopic[] = [
    {
        id: "1",
        label: "Joint Launch Series",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
        slug: "joint-launch-series",
    },
    {
        id: "2",
        label: "Condo Buying",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
        slug: "condo-buying",
    },
    {
        id: "3",
        label: "Education",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
        slug: "education",
    },
    {
        id: "4",
        label: "Lifestyle",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        slug: "lifestyle",
    },
    {
        id: "5",
        label: "Sustainability",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=600&q=80",
        slug: "sustainability",
    },
    {
        id: "6",
        label: "Property Investment",
        image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=600&q=80",
        slug: "property-investment",
    },
    {
        id: "7",
        label: "Home Renovation",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80",
        slug: "home-renovation",
    },
    {
        id: "8",
        label: "Market Insights",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
        slug: "market-insights",
    },
    {
        id: "9",
        label: "Smart Living",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
        slug: "smart-living",
    },
    {
        id: "10",
        label: "Architecture",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
        slug: "architecture",
    },
];

export interface Reel {
    id: string;
    slug: string;
    title: string;
    thumbnail: string;
    duration: string;
    category: "Most Viewed" | "Latest" | "Editor's Pick";
    videoUrl?: string;
}

export const reels: Reel[] = [
    {
        id: "1",
        slug: "singapore-urban-resilience-initiative",
        title: "Singapore Launches Initiative to Enhance Urban Resilience Against C...",
        thumbnail: "https://images.unsplash.com/photo-1524813686514-a57563d77965?w=600&q=80",
        duration: "2:45",
        category: "Most Viewed",
    },
    {
        id: "2",
        slug: "singapore-urban-resilience-part2",
        title: "Singapore Launches Initiative to Enhance Urban Resilience Against C...",
        thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
        duration: "3:12",
        category: "Most Viewed",
    },
    {
        id: "3",
        slug: "singapore-urban-resilience-part3",
        title: "Singapore Launches Initiative to Enhance Urban Resilience Against C...",
        thumbnail: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
        duration: "1:58",
        category: "Latest",
    },
    {
        id: "4",
        slug: "singapore-smart-traffic-management",
        title: "Singapore Introduces New Smart Traffic Management System",
        thumbnail: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=600&q=80",
        duration: "4:20",
        category: "Most Viewed",
    },
    {
        id: "5",
        slug: "singapore-green-building-initiatives",
        title: "Singapore Launches Innovative Green Building Initiatives",
        thumbnail: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=600&q=80",
        duration: "3:35",
        category: "Latest",
    },
    {
        id: "6",
        slug: "singapore-luxury-apartment-surge",
        title: "Singapore Real Estate Market Sees Surge in Luxury Apartment Sales",
        thumbnail: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
        duration: "2:50",
        category: "Editor's Pick",
    },
    {
        id: "7",
        slug: "singapore-real-estate-tech-integration",
        title: "Discover how Singapore is enhancing its real estate landscape by integrat...",
        thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
        duration: "5:10",
        category: "Most Viewed",
    },
    {
        id: "8",
        slug: "singapore-innovative-real-estate",
        title: "Explore Singapore's innovative approach to real estate, where expo...",
        thumbnail: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=600&q=80",
        duration: "3:22",
        category: "Latest",
    },
    {
        id: "9",
        slug: "singapore-sustainable-real-estate",
        title: "Learn about Singapore's commitment to sustainable real estate developm...",
        thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
        duration: "4:05",
        category: "Editor's Pick",
    },
    {
        id: "10",
        slug: "singapore-unprecedented-real-estate-surge",
        title: "In 2023, Singapore's real estate sector is witnessing an unprecedented surg...",
        thumbnail: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=600&q=80",
        duration: "2:30",
        category: "Most Viewed",
    },
    {
        id: "11",
        slug: "singapore-market-booming",
        title: "The year 2023 has seen Singapore's real estate market booming, with a n...",
        thumbnail: "https://images.unsplash.com/photo-1464938050520-ef2571e0d6e0?w=600&q=80",
        duration: "3:48",
        category: "Latest",
    },
    {
        id: "12",
        slug: "singapore-thriving-real-estate",
        title: "Singapore's real estate landscape is thriving in 2023, drawing significant i...",
        thumbnail: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80",
        duration: "4:15",
        category: "Editor's Pick",
    },
    {
        id: "13",
        slug: "singapore-waterfront-living-trends",
        title: "Waterfront Living: Singapore's Most Sought-After Coastal Developments",
        thumbnail: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
        duration: "3:55",
        category: "Most Viewed",
    },
    {
        id: "14",
        slug: "singapore-hdb-transformation",
        title: "The Transformation of HDB Living: Modern Upgrades Across the Island",
        thumbnail: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&q=80",
        duration: "2:18",
        category: "Latest",
    },
    {
        id: "15",
        slug: "singapore-cbd-skyline-evolution",
        title: "CBD Skyline Evolution: How New Towers Are Reshaping Singapore's Core",
        thumbnail: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=600&q=80",
        duration: "5:02",
        category: "Editor's Pick",
    },
    {
        id: "16",
        slug: "singapore-proptech-revolution",
        title: "PropTech Revolution: How Technology Is Changing Property Transactions",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
        duration: "3:40",
        category: "Most Viewed",
    },
    {
        id: "17",
        slug: "singapore-landed-property-guide",
        title: "A Visual Guide to Singapore's Most Prestigious Landed Property Enclaves",
        thumbnail: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        duration: "4:30",
        category: "Latest",
    },
    {
        id: "18",
        slug: "singapore-eco-town-tengah",
        title: "Inside Tengah: Singapore's First Eco-Town Takes Shape",
        thumbnail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
        duration: "3:15",
        category: "Editor's Pick",
    },
    {
        id: "19",
        slug: "singapore-district-15-hidden-gems",
        title: "District 15 Hidden Gems: Uncovering East Coast's Best-Kept Property Secrets",
        thumbnail: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",
        duration: "4:45",
        category: "Most Viewed",
    },
    {
        id: "20",
        slug: "singapore-orchard-road-revival",
        title: "Orchard Road Revival: Luxury Residential Projects Transforming the Strip",
        thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
        duration: "3:28",
        category: "Most Viewed",
    },
    {
        id: "21",
        slug: "singapore-mrt-property-hotspots",
        title: "MRT Effect: Property Hotspots Emerging Along New Thomson-East Coast Line",
        thumbnail: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=600&q=80",
        duration: "5:15",
        category: "Most Viewed",
    },
    {
        id: "22",
        slug: "singapore-sentosa-cove-lifestyle",
        title: "Sentosa Cove Lifestyle: A Day in Singapore's Most Exclusive Waterfront Enclave",
        thumbnail: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        duration: "6:02",
        category: "Most Viewed",
    },
    {
        id: "23",
        slug: "singapore-smart-home-tech-2026",
        title: "Smart Home Technology 2026: What Every Singapore Homeowner Should Know",
        thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
        duration: "3:50",
        category: "Most Viewed",
    },
    {
        id: "24",
        slug: "singapore-bukit-timah-landed",
        title: "Bukit Timah's Landed Legacy: Why This District Remains Singapore's Crown Jewel",
        thumbnail: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
        duration: "4:10",
        category: "Most Viewed",
    },
    {
        id: "25",
        slug: "singapore-marina-bay-skyline",
        title: "Marina Bay Skyline: The Engineering Behind Singapore's Iconic Waterfront",
        thumbnail: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=600&q=80",
        duration: "5:30",
        category: "Most Viewed",
    },
    {
        id: "26",
        slug: "singapore-reit-performance-review",
        title: "Singapore REIT Performance Review: Top Performers of the Year",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
        duration: "3:55",
        category: "Most Viewed",
    },
    {
        id: "27",
        slug: "singapore-punggol-digital-district",
        title: "Punggol Digital District: Singapore's Next-Generation Business Hub",
        thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
        duration: "4:22",
        category: "Latest",
    },
    {
        id: "28",
        slug: "singapore-holland-village-charm",
        title: "Holland Village Charm: Why This Neighbourhood Remains a Favourite Among Expats",
        thumbnail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
        duration: "3:18",
        category: "Latest",
    },
    {
        id: "29",
        slug: "singapore-clementi-transformation",
        title: "Clementi's Transformation: From Suburb to Self-Sufficient Urban Town",
        thumbnail: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&q=80",
        duration: "4:40",
        category: "Latest",
    },
    {
        id: "30",
        slug: "singapore-energy-efficient-homes",
        title: "Energy Efficient Homes: How Singapore Is Leading Asia's Green Building Movement",
        thumbnail: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=600&q=80",
        duration: "3:05",
        category: "Latest",
    },
    {
        id: "31",
        slug: "singapore-tiong-bahru-heritage",
        title: "Tiong Bahru Heritage Walk: Art Deco Architecture Meets Modern Living",
        thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
        duration: "2:55",
        category: "Latest",
    },
    {
        id: "32",
        slug: "singapore-woodlands-regional-centre",
        title: "Woodlands Regional Centre: The Northern Gateway Reshaping Property Values",
        thumbnail: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=600&q=80",
        duration: "4:08",
        category: "Latest",
    },
    {
        id: "33",
        slug: "singapore-condo-pool-facilities",
        title: "Condo Facilities Ranked: The Most Impressive Pool and Gym Setups in Singapore",
        thumbnail: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
        duration: "5:20",
        category: "Latest",
    },
    {
        id: "34",
        slug: "singapore-jurong-lake-district",
        title: "Jurong Lake District Vision: Singapore's Ambitious Second CBD Masterplan",
        thumbnail: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=600&q=80",
        duration: "4:35",
        category: "Latest",
    },
    {
        id: "35",
        slug: "singapore-bishan-family-living",
        title: "Bishan for Families: Why This Central Town Tops the Liveability Charts",
        thumbnail: "https://images.unsplash.com/photo-1464938050520-ef2571e0d6e0?w=600&q=80",
        duration: "3:42",
        category: "Editor's Pick",
    },
    {
        id: "36",
        slug: "singapore-pasir-ris-coastal-living",
        title: "Pasir Ris Coastal Living: The Allure of Singapore's Eastern Waterfront",
        thumbnail: "https://images.unsplash.com/photo-1524813686514-a57563d77965?w=600&q=80",
        duration: "4:00",
        category: "Editor's Pick",
    },
    {
        id: "37",
        slug: "singapore-novena-medical-hub",
        title: "Novena Medical Hub: How Healthcare Infrastructure Drives Property Demand",
        thumbnail: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=600&q=80",
        duration: "3:30",
        category: "Editor's Pick",
    },
    {
        id: "38",
        slug: "singapore-tanjong-pagar-revival",
        title: "Tanjong Pagar's Revival: From Heritage District to Modern Mixed-Use Precinct",
        thumbnail: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=600&q=80",
        duration: "5:45",
        category: "Editor's Pick",
    },
    {
        id: "39",
        slug: "singapore-cross-island-line-impact",
        title: "Cross Island Line: How Singapore's Longest MRT Line Will Reshape Property",
        thumbnail: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
        duration: "4:18",
        category: "Editor's Pick",
    },
    {
        id: "40",
        slug: "singapore-paya-lebar-quarter",
        title: "Paya Lebar Quarter: The Transformation of a Former Industrial Zone",
        thumbnail: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",
        duration: "3:52",
        category: "Editor's Pick",
    },
    {
        id: "41",
        slug: "singapore-rooftop-gardens-trend",
        title: "Rooftop Gardens: Singapore's Emerging Trend in High-Rise Sustainable Living",
        thumbnail: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80",
        duration: "2:48",
        category: "Editor's Pick",
    },
    {
        id: "42",
        slug: "singapore-tampines-regional-hub",
        title: "Tampines Regional Centre: Eastern Singapore's Thriving Commercial Heart",
        thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
        duration: "4:25",
        category: "Editor's Pick",
    },
];

export interface NewLaunchItem {
    id: string;
    slug: string;
    title: string;
    excerpt: string;
    image: string;
    category: "Most Viewed" | "Latest" | "Editor's Pick";
    readTime: string;
    isHero?: boolean;
}

export const newLaunchSeries: NewLaunchItem[] = [
    {
        id: "1",
        slug: "cta-luxury-residences-meyer",
        title: "CTA to Develop Luxury Residences in Meyer Road",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Most Viewed",
        readTime: "5 mins read",
    },
    {
        id: "2",
        slug: "hdb-eco-friendly-punggol-northshore",
        title: "HDB Unveils Plans for Eco-Friendly Housing in Punggol Northshore",
        excerpt: "HDB is set to introduce sustainable living concepts in Punggol Northshore with new eco-friendly housing pr...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Most Viewed",
        readTime: "4 mins read",
    },
    {
        id: "3",
        slug: "capitaland-ascendas-logistics-jurong-east",
        title: "CapitaLand Ascendas REIT Acquires Logistics Hub in Jurong East",
        excerpt: "CapitaLand Ascendas REIT expands its portfolio with the acquisition of a prime logistics hub in Jurong East...",
        image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&q=80",
        category: "Most Viewed",
        readTime: "6 mins read",
    },
    {
        id: "4",
        slug: "cdl-new-retail-spaces-bugis",
        title: "City Developments Limited Launches New Retail Spaces in Bugis",
        excerpt: "CDL is set to launch a fresh wave of retail spaces aimed at enhancing the sh...",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        category: "Most Viewed",
        readTime: "4 mins read",
    },
    {
        id: "5",
        slug: "surbana-jurong-urban-tampines",
        title: "Surbana Jurong to Lead Urban Development Projects in Tampines",
        excerpt: "Surbana Jurong has been appointed to oversee multiple urban development projects in the Tampines ar...",
        image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        category: "Most Viewed",
        readTime: "5 mins read",
    },
    {
        id: "6",
        slug: "frasers-innovative-office-one-north",
        title: "Frasers Property Reveals Innovative Office Spaces in One North",
        excerpt: "Frasers Property unveils plans for modern office spaces designed to foster collaboration and creativity in One...",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
        category: "Most Viewed",
        readTime: "5 mins read",
    },
    {
        id: "7",
        slug: "ascendas-mixed-use-changi",
        title: "Ascendas Singbridge Announces New Mixed-Use Development in Changi",
        excerpt: "Ascendas Singbridge reveals plans for a new mixed-use development that integrates residential, commer...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Most Viewed",
        readTime: "6 mins read",
    },
    {
        id: "8",
        slug: "guocoland-smart-home-district",
        title: "GuocoLand Launches Smart Home Initiatives in New District",
        excerpt: "GuocoLand is set to introduce smart home technologies in its latest district development, enhanc...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Most Viewed",
        readTime: "4 mins read",
    },
    {
        id: "9",
        slug: "mapletree-new-industrial-park",
        title: "Mapletree Investments Expands Portfolio with New Industrial Park",
        excerpt: "Mapletree Investments announces the launch of a state-of-the-art industrial park aimed at meeting the...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "Most Viewed",
        readTime: "5 mins read",
    },
    {
        id: "10",
        slug: "oxley-commercial-novena-landmark",
        title: "Oxley Holdings Debuts New Landmark Commercial Development in Novena",
        excerpt: "Oxley Holdings has unveiled plans for a landmark commercial development in Novena, featuring cuttin...",
        image: "https://images.unsplash.com/photo-1464938050520-ef2571e0d6e0?w=800&q=80",
        category: "Most Viewed",
        readTime: "7 mins read",
    },
    {
        id: "11",
        slug: "surbana-green-infrastructure-govt",
        title: "Surbana Jurong Partners with Government on Green Infrastructure...",
        excerpt: "Surbana Jurong collaborates with government agencies to enhance urban resilience through innova...",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        category: "Most Viewed",
        readTime: "6 mins read",
    },
    {
        id: "12",
        slug: "keppel-waterfront-tanjong",
        title: "Keppel Land Announces New Waterfront Residential Project in Tanj...",
        excerpt: "Keppel Land plans to develop a new waterfront residential project in Tanjong Pagar, promising stunn...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Most Viewed",
        readTime: "5 mins read",
    },
    {
        id: "13",
        slug: "lendlease-one-holland-village",
        title: "Lendlease Unveils Phase 2 of One Holland Village Integrated Development",
        excerpt: "Lendlease continues its transformation of Holland Village with the second phase featuring premium residences and retail...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Latest",
        readTime: "5 mins read",
    },
    {
        id: "14",
        slug: "uol-avenue-south-residence",
        title: "UOL Group Launches Avenue South Residence Tower 2 at Silat Avenue",
        excerpt: "UOL Group introduces the second tower of its landmark Avenue South Residence, offering panoramic views of the southern coastline...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Latest",
        readTime: "4 mins read",
    },
    {
        id: "15",
        slug: "allgreen-fourth-avenue-residences",
        title: "Allgreen Properties Reveals Fourth Avenue Residences in Bukit Timah",
        excerpt: "Allgreen Properties presents an exclusive collection of luxury homes in the prestigious Bukit Timah neighbourhood...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Latest",
        readTime: "6 mins read",
    },
    {
        id: "16",
        slug: "wing-tai-cuscaden-reserve",
        title: "Wing Tai Holdings Debuts Cuscaden Reserve Along Orchard Boulevard",
        excerpt: "Wing Tai Holdings launches an ultra-luxury residential project at the heart of Orchard Road with world-class amenities...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Latest",
        readTime: "5 mins read",
    },
    {
        id: "17",
        slug: "far-east-organization-tengah",
        title: "Far East Organization Announces New BTO-Adjacent Private Condo in Tengah",
        excerpt: "Far East Organization targets young families with an affordable private condominium adjacent to Tengah's new town centre...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Latest",
        readTime: "4 mins read",
    },
    {
        id: "18",
        slug: "hongkong-land-marina-view",
        title: "Hongkong Land Plans Premium Waterfront Residences at Marina View",
        excerpt: "Hongkong Land enters Singapore's residential market with a premium waterfront development at Marina View...",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        category: "Latest",
        readTime: "7 mins read",
    },
    {
        id: "19",
        slug: "singhaiyi-parc-greenwich",
        title: "SingHaiyi Group Launches Parc Greenwich Executive Condo in Yio Chu Kang",
        excerpt: "SingHaiyi Group introduces a new executive condominium in Yio Chu Kang with family-friendly layouts and lush landscaping...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "Latest",
        readTime: "4 mins read",
    },
    {
        id: "20",
        slug: "city-dev-irwell-hill",
        title: "CDL Unveils Irwell Hill Residences: Freehold Living Near Orchard",
        excerpt: "City Developments Limited presents a rare freehold residential development just minutes from Orchard Road...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "Latest",
        readTime: "5 mins read",
    },
    {
        id: "21",
        slug: "qingjian-jadescape",
        title: "Qingjian Realty's JadeScape: Bishan's Largest Integrated Development",
        excerpt: "Qingjian Realty transforms the former Shunfu Ville site into a sprawling integrated development with over 1,200 units...",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        category: "Latest",
        readTime: "6 mins read",
    },
    {
        id: "22",
        slug: "guocoland-midtown-modern",
        title: "GuocoLand's Midtown Modern: Redefining City Living at Bugis",
        excerpt: "GuocoLand's mixed-use Midtown Modern development brings a new standard of urban living to the Bugis-Beach Road corridor...",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        category: "Latest",
        readTime: "5 mins read",
    },
    {
        id: "23",
        slug: "capitaland-canninghill-piers",
        title: "CapitaLand's Canninghill Piers: Riverside Living at the Former Liang Court",
        excerpt: "CapitaLand transforms the iconic Liang Court site into a landmark riverside integrated development...",
        image: "https://images.unsplash.com/photo-1524813686514-a57563d77965?w=800&q=80",
        category: "Latest",
        readTime: "6 mins read",
    },
    {
        id: "24",
        slug: "frasers-riviere",
        title: "Frasers Property's Rivière: Ultra-Luxury Living Along the Singapore River",
        excerpt: "Frasers Property unveils Rivière, offering bespoke luxury residences with uninterrupted views of the Singapore River...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Latest",
        readTime: "5 mins read",
    },
    {
        id: "25",
        slug: "ecoworld-bukit-batok-west",
        title: "EcoWorld Debuts Nature-Inspired Condo at Bukit Batok West Avenue",
        excerpt: "EcoWorld International brings its signature nature-centric design philosophy to a new condominium in Bukit Batok...",
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
        category: "Editor's Pick",
        readTime: "4 mins read",
    },
    {
        id: "26",
        slug: "keppel-bay-tower-residences",
        title: "Keppel Bay Tower Residences: Harbourfront's New Crown Jewel",
        excerpt: "Keppel Land introduces premium residences atop Keppel Bay Tower with panoramic sea views and yacht club access...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "Editor's Pick",
        readTime: "6 mins read",
    },
    {
        id: "27",
        slug: "oxley-pasir-ris-waterfront",
        title: "Oxley Holdings' Pasir Ris Waterfront Development with Direct Beach Access",
        excerpt: "Oxley Holdings announces a unique waterfront condominium in Pasir Ris with direct access to the beach and cycling paths...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Editor's Pick",
        readTime: "5 mins read",
    },
    {
        id: "28",
        slug: "tee-land-novena-boutique",
        title: "TEE Land Launches Boutique Residences in Novena Medical Hub Precinct",
        excerpt: "TEE Land introduces a compact boutique development near Novena, targeting healthcare professionals and investors...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Editor's Pick",
        readTime: "4 mins read",
    },
    {
        id: "29",
        slug: "sim-lian-treasure-tampines",
        title: "Sim Lian's Treasure at Tampines: 2,203 Units in Singapore's Largest Condo",
        excerpt: "Sim Lian Group breaks records with the largest condominium development in Singapore, offering remarkable value...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "Editor's Pick",
        readTime: "7 mins read",
    },
    {
        id: "30",
        slug: "allgreen-royalgreen-bukit-timah",
        title: "Allgreen's RoyalGreen: Freehold Sanctuary in the Heart of Bukit Timah",
        excerpt: "Allgreen Properties unveils a freehold development surrounded by lush greenery near the Bukit Timah Nature Reserve...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Editor's Pick",
        readTime: "5 mins read",
    },
    {
        id: "31",
        slug: "soilbuild-soleil-sinaran",
        title: "Soilbuild Group's Soleil @ Sinaran: City Fringe Living Near Novena MRT",
        excerpt: "Soilbuild Group presents a city-fringe condominium with excellent connectivity and proximity to Novena MRT station...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Editor's Pick",
        readTime: "4 mins read",
    },
    {
        id: "32",
        slug: "hatten-land-mrt-integrated",
        title: "Hatten Land's First MRT-Integrated Residential Project in Woodlands",
        excerpt: "Hatten Land debuts a transit-oriented development directly integrated with Woodlands MRT interchange...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "Editor's Pick",
        readTime: "5 mins read",
    },
    {
        id: "33",
        slug: "uol-meyer-house",
        title: "UOL Group's Meyer House: Ultra-Exclusive 56-Unit Seafront Residence",
        excerpt: "UOL Group launches Meyer House, an ultra-luxury development of just 56 units along the coveted Meyer Road seafront...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Editor's Pick",
        readTime: "6 mins read",
    },
    {
        id: "34",
        slug: "wing-tai-le-nouvel-ardmore",
        title: "Wing Tai's Le Nouvel Ardmore: Redefining Ultra-Luxury in District 10",
        excerpt: "Wing Tai Holdings sets a new benchmark for luxury living with Le Nouvel Ardmore's award-winning architecture...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Editor's Pick",
        readTime: "7 mins read",
    },
    {
        id: "35",
        slug: "cdl-whistler-grand-west-coast",
        title: "CDL's Whistler Grand: West Coast's Most Anticipated Launch of 2026",
        excerpt: "City Developments Limited introduces Whistler Grand with stunning West Coast views and resort-style amenities...",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        category: "Editor's Pick",
        readTime: "5 mins read",
    },
    {
        id: "36",
        slug: "capitaland-sengkang-grand-residences",
        title: "CapitaLand's Sengkang Grand Residences: Integrated Living at Its Best",
        excerpt: "CapitaLand launches an integrated development at Sengkang Central combining residences, retail, and community amenities...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Editor's Pick",
        readTime: "5 mins read",
    },
];

export type HomeTourCategory = "Condo" | "HDB" | "Landed" | "Apartment" | "Commercial";

export interface HomeTourItem {
    id: string;
    slug: string;
    title: string;
    excerpt: string;
    image: string;
    category: HomeTourCategory;
    readTime: string;
    isHero?: boolean;
}

export const homeTourSeries: HomeTourItem[] = [
    {
        id: "1",
        slug: "springdale-view-freehold-6br",
        title: "Springdale View – Freehold 6-Bedroom Inter-Terrace in District 26 L...",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "2",
        slug: "riverfront-residences-2br",
        title: "Riverfront Residences – 2-Bedroom with 1,066sqft in D19 | 99-Year Leaseh...",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "3",
        slug: "springdale-view-freehold-6br-v2",
        title: "Springdale View – Freehold 6-Bedroom Inter-Terrace in District 26 L...",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Condo",
        readTime: "6 mins read",
    },
    {
        id: "4",
        slug: "lakeside-garden-5br-semi-d",
        title: "Lakeside Garden – 5-Bedroom Semi-Detached in District 22 | $3,250,000 L...",
        excerpt: "This expansive semi-detached home in Lakeside Garden offers generous living spaces and easy access to prime...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Landed",
        readTime: "5 mins read",
    },
    {
        id: "5",
        slug: "marina-bay-suites-4br",
        title: "Marina Bay Suites – 4-Bedroom Apartment with 1,100 sqft in D01 | Fre...",
        excerpt: "This stunning unit offers breathtaking views of the Marina Bay skyline with premium finishes throughout...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Apartment",
        readTime: "4 mins read",
    },
    {
        id: "6",
        slug: "horizon-residences-3br",
        title: "Horizon Residences – 3-Bedroom Apartment in District 11 | 99-Year Lea...",
        excerpt: "Set in classic design, this spacious unit features well-laid-out rooms, a private balcony spanning living...",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "7",
        slug: "sunset-grove-4br-bungalow",
        title: "Sunset Grove – 4-Bedroom Bungalow in District 11 | $3,000,000 | Linda Cho...",
        excerpt: "This true bungalow offers impressive living spaces and a sprawling garden, perfect for families seeking...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Landed",
        readTime: "6 mins read",
    },
    {
        id: "8",
        slug: "peak-of-bukit-timah-2br",
        title: "The Peak of Bukit Timah – 2-Bedroom Condominium with 1,200 sqft in D21...",
        excerpt: "Nestled within a lush greenery, this condominium unit sits high above the city, enjoying cool breezes...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "9",
        slug: "springdale-view-freehold-6br-v3",
        title: "Springdale View – Freehold 6-Bedroom Inter-Terrace in District 26 L...",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "10",
        slug: "east-coast-haven-5br",
        title: "East Coast Haven – 5-Bedroom Detached House in District 15 | $4,5M...",
        excerpt: "This spacious haven in Singapore's favourite east-side district offers generous living with coastal ch...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Landed",
        readTime: "7 mins read",
    },
    {
        id: "11",
        slug: "clydesdale-residences-2br",
        title: "Clydesdale Residences – 2-Bedroom Unit in D07 | Freehold | $1,960,000 | Ad...",
        excerpt: "This finely curated condominium blends modern design with timeless elegance in the heart of the MRT...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Condo",
        readTime: "4 mins read",
    },
    {
        id: "12",
        slug: "springdale-view-freehold-6br-v4",
        title: "Springdale View – Freehold 6-Bedroom Inter-Terrace in District 26 L...",
        excerpt: "CTA is planning a new luxury residential project on Meyer Road, capitalising on the high-end property ma...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "13",
        slug: "tampines-greenview-4rm-hdb",
        title: "Tampines GreenView – 4-Room HDB Flat with Unblocked View | $580,000",
        excerpt: "This well-maintained 4-room HDB flat in Tampines offers panoramic unblocked views and convenient access...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "14",
        slug: "bishan-5rm-premium-hdb",
        title: "Bishan Premium – 5-Room HDB Maisonette with Loft in Mature Estate",
        excerpt: "A rare 5-room maisonette in Bishan with a spacious loft area, walking distance to Junction 8 and MRT...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "15",
        slug: "toa-payoh-3rm-hdb",
        title: "Toa Payoh Central – 3-Room Renovated HDB in Heart of Town | $420,000",
        excerpt: "Newly renovated 3-room HDB in the iconic Toa Payoh estate, with modern finishes and easy MRT access...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "16",
        slug: "queenstown-executive-hdb",
        title: "Queenstown Executive – Spacious 5-Room DBSS with City Views | $780,000",
        excerpt: "This executive HDB in Queenstown offers rare city views, premium DBSS finishes, and excellent connectivity...",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "17",
        slug: "punggol-waterway-4rm-hdb",
        title: "Punggol Waterway – 4-Room BTO with Waterway View | Move-In Ready",
        excerpt: "Brand new BTO flat along Punggol Waterway with scenic canal views and modern town amenities...",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "18",
        slug: "bukit-timah-good-class-bungalow",
        title: "Bukit Timah – Good Class Bungalow with Pool on 15,000 sqft Land",
        excerpt: "An exceptional Good Class Bungalow in prime Bukit Timah with lush tropical landscaping and a resort-style pool...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Landed",
        readTime: "7 mins read",
    },
    {
        id: "19",
        slug: "siglap-corner-terrace",
        title: "Siglap – Renovated Corner Terrace with Rooftop Deck | District 15",
        excerpt: "A beautifully renovated corner terrace in Siglap featuring a rooftop entertainment deck and modern interiors...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Landed",
        readTime: "5 mins read",
    },
    {
        id: "20",
        slug: "orchard-boulevard-penthouse",
        title: "Orchard Boulevard – 4-Bedroom Penthouse Apartment | 3,200 sqft | $8.5M",
        excerpt: "An ultra-luxurious penthouse in the heart of Orchard Road with wraparound terraces and panoramic city views...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Apartment",
        readTime: "6 mins read",
    },
    {
        id: "21",
        slug: "river-valley-2br-apartment",
        title: "River Valley – 2-Bedroom Apartment with Balcony | 850 sqft | Freehold",
        excerpt: "A compact yet stylish 2-bedroom apartment near Robertson Quay with river views and vibrant dining options...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Apartment",
        readTime: "4 mins read",
    },
    {
        id: "22",
        slug: "tanjong-pagar-studio-apartment",
        title: "Tanjong Pagar – Studio Apartment with City Views | 520 sqft | $1.1M",
        excerpt: "An efficient studio unit in the CBD with stunning views of Tanjong Pagar and easy access to Chinatown MRT...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Apartment",
        readTime: "3 mins read",
    },
    {
        id: "23",
        slug: "bugis-shophouse-commercial",
        title: "Bugis Shophouse – Restored 2-Storey Conservation Unit | Commercial Use",
        excerpt: "A beautifully restored conservation shophouse in the Bugis-Kampong Glam precinct, ideal for F&B or retail...",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "24",
        slug: "robinson-road-office-unit",
        title: "Robinson Road – Grade A Office Unit | 2,500 sqft | CBD Core",
        excerpt: "Premium Grade A office space in Robinson Road with floor-to-ceiling windows and panoramic harbour views...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "25",
        slug: "alexandra-retail-unit",
        title: "Alexandra – Ground Floor Retail Unit in Mixed-Use Development | 1,200 sqft",
        excerpt: "High-visibility retail space in Alexandra's bustling mixed-use hub, perfect for lifestyle brands and F&B concepts...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "26",
        slug: "harbourfront-industrial-unit",
        title: "HarbourFront – B1 Industrial Unit with Sea View | 3,000 sqft | $2.8M",
        excerpt: "A rare B1 industrial unit at HarbourFront with sea views, suitable for showroom, office, or light industrial use...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "27",
        slug: "parc-clematis-3br-condo",
        title: "Parc Clematis – 3-Bedroom Condo with 1,100 sqft in D05 | $1,580,000",
        excerpt: "A modern 3-bedroom unit in Parc Clematis with lush landscape views and resort-style facilities...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "28",
        slug: "meyer-mansion-2br-condo",
        title: "Meyer Mansion – 2-Bedroom Luxury Condo in District 15 | Freehold | $2.1M",
        excerpt: "An exquisite 2-bedroom unit at Meyer Mansion offering unblocked sea views and premium finishes throughout...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Condo",
        readTime: "4 mins read",
    },
    {
        id: "29",
        slug: "one-pearl-bank-1br-condo",
        title: "One Pearl Bank – 1-Bedroom Condo with City Views | 506 sqft | $1,050,000",
        excerpt: "A beautifully designed 1-bedroom unit in the iconic One Pearl Bank with breathtaking city panoramas...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Condo",
        readTime: "3 mins read",
    },
    {
        id: "30",
        slug: "avenue-south-residence-3br",
        title: "Avenue South Residence – 3-Bedroom Premium in D03 | 99-Year | $1,780,000",
        excerpt: "A spacious 3-bedroom unit in Avenue South Residence with stunning views of the southern waterfront...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "31",
        slug: "normanton-park-2br-condo",
        title: "Normanton Park – 2-Bedroom Condo with Garden View | 753 sqft | $1,320,000",
        excerpt: "A tranquil 2-bedroom unit at Normanton Park surrounded by lush greenery and nature trails...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Condo",
        readTime: "4 mins read",
    },
    {
        id: "32",
        slug: "midtown-modern-studio-condo",
        title: "Midtown Modern – Studio Unit in Bugis | 463 sqft | $1,180,000",
        excerpt: "A sleek studio unit at Midtown Modern directly connected to Bugis MRT, perfect for young professionals...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Condo",
        readTime: "3 mins read",
    },
    {
        id: "33",
        slug: "the-reef-at-kings-dock-2br",
        title: "The Reef at King's Dock – 2-Bedroom with Waterfront Views | Freehold",
        excerpt: "An exclusive waterfront living experience at King's Dock with direct marina access and stunning sunset views...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Condo",
        readTime: "5 mins read",
    },
    {
        id: "34",
        slug: "leedon-green-4br-condo",
        title: "Leedon Green – 4-Bedroom Luxury Unit in D10 | 2,100 sqft | $4,500,000",
        excerpt: "An ultra-premium 4-bedroom unit nestled in the prestigious Leedon Heights enclave with lush garden views...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Condo",
        readTime: "6 mins read",
    },
    {
        id: "35",
        slug: "ki-residences-3br-condo",
        title: "Ki Residences – 3-Bedroom with Sunset View in D23 | 99-Year | $1,450,000",
        excerpt: "A serene 3-bedroom retreat at Ki Residences with panoramic sunset views over Bukit Timah hills...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Condo",
        readTime: "4 mins read",
    },
    {
        id: "36",
        slug: "canninghill-piers-1br-condo",
        title: "CanningHill Piers – 1-Bedroom at Clarke Quay | 538 sqft | $1,380,000",
        excerpt: "A vibrant 1-bedroom unit at CanningHill Piers overlooking the Singapore River and Clarke Quay nightlife...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "Condo",
        readTime: "3 mins read",
    },
    {
        id: "37",
        slug: "the-watergardens-at-canberra-2br",
        title: "The Watergardens at Canberra – 2-Bedroom with Pool View | 743 sqft",
        excerpt: "A family-friendly 2-bedroom condo at Canberra with lush waterscape features and excellent schools nearby...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "Condo",
        readTime: "4 mins read",
    },
    {
        id: "38",
        slug: "clementi-peaks-5rm-hdb",
        title: "Clementi Peaks – 5-Room HDB with Panoramic Views | $720,000",
        excerpt: "A well-renovated 5-room HDB in Clementi with stunning panoramic views of the West Coast skyline...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "39",
        slug: "woodlands-crescent-4rm-hdb",
        title: "Woodlands Crescent – 4-Room BTO with Modern Finishes | $480,000",
        excerpt: "A brand new 4-room BTO in Woodlands with contemporary design, near MRT and shopping amenities...",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "40",
        slug: "sengkang-rivervale-5rm-hdb",
        title: "Sengkang Rivervale – 5-Room Executive with River View | $650,000",
        excerpt: "A spacious executive flat in Sengkang Rivervale with scenic river views and excellent waterway park access...",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "41",
        slug: "ang-mo-kio-3rm-hdb",
        title: "Ang Mo Kio – Renovated 3-Room HDB Near MRT | $380,000",
        excerpt: "A freshly renovated 3-room flat in the heart of Ang Mo Kio, steps away from AMK Hub and MRT station...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "42",
        slug: "jurong-east-4rm-dbss",
        title: "Jurong East – 4-Room DBSS with Lake View | Near J-Cube | $580,000",
        excerpt: "A premium DBSS flat in Jurong East overlooking Jurong Lake with excellent transport connectivity...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "43",
        slug: "yishun-greenwalk-5rm-hdb",
        title: "Yishun GreenWalk – 5-Room Flat with Garden Views | $520,000",
        excerpt: "A well-maintained 5-room flat in Yishun surrounded by lush greenery and close to Northpoint City...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "HDB",
        readTime: "3 mins read",
    },
    {
        id: "44",
        slug: "bukit-batok-exec-maisonette",
        title: "Bukit Batok – Executive Maisonette with Loft | Spacious 1,600 sqft",
        excerpt: "A rare executive maisonette in Bukit Batok featuring a generous loft space and mature estate amenities...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "HDB",
        readTime: "5 mins read",
    },
    {
        id: "45",
        slug: "dawson-skyterrace-4rm",
        title: "SkyTerrace @ Dawson – 4-Room Premium with City Skyline Views",
        excerpt: "An award-winning HDB development in Dawson with sky terraces, green features and stunning city views...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "46",
        slug: "bedok-reservoir-5rm-hdb",
        title: "Bedok Reservoir – 5-Room Flat with Reservoir View | $620,000",
        excerpt: "A corner unit 5-room flat in Bedok with serene reservoir views and proximity to Bedok Mall...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "HDB",
        readTime: "4 mins read",
    },
    {
        id: "47",
        slug: "holland-grove-semi-d",
        title: "Holland Grove – Freehold Semi-Detached with Pool | District 10 | $6.5M",
        excerpt: "A stunning freehold semi-detached home in Holland Grove with a private pool and lush tropical garden...",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "Landed",
        readTime: "6 mins read",
    },
    {
        id: "48",
        slug: "frankel-avenue-terrace",
        title: "Frankel Avenue – Renovated Terrace House in D15 | Freehold | $3.8M",
        excerpt: "A beautifully renovated terrace home along Frankel Avenue with modern interiors and coastal charm...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Landed",
        readTime: "5 mins read",
    },
    {
        id: "49",
        slug: "nassim-road-gcb",
        title: "Nassim Road – Good Class Bungalow on 20,000 sqft | Ultra Prime | $35M",
        excerpt: "An exceptional GCB on Nassim Road with a grand driveway, resort-style pool, and sprawling tropical gardens...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Landed",
        readTime: "7 mins read",
    },
    {
        id: "50",
        slug: "kovan-corner-terrace",
        title: "Kovan – Corner Terrace with Rooftop Jacuzzi | 3,200 sqft | $4.2M",
        excerpt: "A modern corner terrace in Kovan with a rooftop jacuzzi, home lift, and smart home features throughout...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Landed",
        readTime: "5 mins read",
    },
    {
        id: "51",
        slug: "serangoon-garden-detached",
        title: "Serangoon Garden – Detached House with 8,000 sqft Land | $7.8M",
        excerpt: "A sprawling detached home in the charming Serangoon Garden estate with ample land for expansion...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Landed",
        readTime: "6 mins read",
    },
    {
        id: "52",
        slug: "joo-chiat-conservation-terrace",
        title: "Joo Chiat – Conservation Terrace with Modern Extension | Freehold",
        excerpt: "A rare conservation terrace in Joo Chiat blending heritage charm with a sleek modern rear extension...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Landed",
        readTime: "5 mins read",
    },
    {
        id: "53",
        slug: "greenwood-avenue-semi-d",
        title: "Greenwood Avenue – Semi-D with Basement Garage | D11 | $5.5M",
        excerpt: "A well-built semi-detached home along Greenwood Avenue with a basement garage and lush garden setting...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "Landed",
        readTime: "6 mins read",
    },
    {
        id: "54",
        slug: "watten-estate-bungalow",
        title: "Watten Estate – Rebuilt Bungalow with Lift | 7,500 sqft Land | $12M",
        excerpt: "A fully rebuilt bungalow in prestigious Watten Estate with a private lift, wine cellar, and infinity pool...",
        image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&q=80",
        category: "Landed",
        readTime: "7 mins read",
    },
    {
        id: "55",
        slug: "mountbatten-inter-terrace",
        title: "Mountbatten – Inter-Terrace with Attic Room | Near MRT | $3.2M",
        excerpt: "A cosy inter-terrace in Mountbatten with an attic room, walking distance to Mountbatten MRT station...",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        category: "Landed",
        readTime: "4 mins read",
    },
    {
        id: "56",
        slug: "novena-3br-apartment",
        title: "Novena – 3-Bedroom Apartment with City Views | 1,200 sqft | $2.1M",
        excerpt: "A stylish 3-bedroom apartment in Novena with panoramic city views and excellent medical hub proximity...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Apartment",
        readTime: "4 mins read",
    },
    {
        id: "57",
        slug: "farrer-park-2br-apartment",
        title: "Farrer Park – 2-Bedroom Apartment with Balcony | 780 sqft | Freehold",
        excerpt: "A compact freehold apartment near Farrer Park MRT with a spacious balcony and vibrant neighbourhood...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Apartment",
        readTime: "3 mins read",
    },
    {
        id: "58",
        slug: "telok-blangah-penthouse",
        title: "Telok Blangah – Penthouse Apartment with Rooftop Terrace | 2,800 sqft",
        excerpt: "An expansive penthouse in Telok Blangah with a private rooftop terrace and sweeping harbour views...",
        image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
        category: "Apartment",
        readTime: "6 mins read",
    },
    {
        id: "59",
        slug: "tiong-bahru-1br-apartment",
        title: "Tiong Bahru – 1-Bedroom Heritage Apartment | 550 sqft | $980,000",
        excerpt: "A charming 1-bedroom apartment in the iconic Tiong Bahru neighbourhood with art deco character...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Apartment",
        readTime: "3 mins read",
    },
    {
        id: "60",
        slug: "katong-duplex-apartment",
        title: "Katong – Duplex Apartment with Sea Breeze | 1,600 sqft | $2.4M",
        excerpt: "A unique duplex apartment in Katong with double-volume ceilings and refreshing sea breezes...",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        category: "Apartment",
        readTime: "5 mins read",
    },
    {
        id: "61",
        slug: "buona-vista-studio-apartment",
        title: "Buona Vista – Studio Apartment Near One-North | 480 sqft | $850,000",
        excerpt: "An efficient studio unit near the One-North tech hub, ideal for professionals working in the R&D corridor...",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
        category: "Apartment",
        readTime: "3 mins read",
    },
    {
        id: "62",
        slug: "holland-village-3br-apartment",
        title: "Holland Village – 3-Bedroom Apartment with Greenery Views | 1,100 sqft",
        excerpt: "A laid-back 3-bedroom apartment overlooking the leafy Holland Village enclave with bohemian dining nearby...",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        category: "Apartment",
        readTime: "4 mins read",
    },
    {
        id: "63",
        slug: "dempsey-hill-4br-apartment",
        title: "Dempsey Hill – 4-Bedroom Luxury Apartment | 2,200 sqft | $3.8M",
        excerpt: "A prestigious 4-bedroom apartment near Dempsey Hill's dining and art galleries with lush surroundings...",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        category: "Apartment",
        readTime: "5 mins read",
    },
    {
        id: "64",
        slug: "east-coast-beachfront-apartment",
        title: "East Coast – Beachfront 2-Bedroom Apartment | 900 sqft | Freehold",
        excerpt: "A rare beachfront apartment along East Coast with direct park access and stunning sea views...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "Apartment",
        readTime: "4 mins read",
    },
    {
        id: "65",
        slug: "paya-lebar-square-office",
        title: "Paya Lebar Square – Grade A Office Space | 1,800 sqft | Near MRT",
        excerpt: "A modern Grade A office unit in Paya Lebar Square with direct MRT access and flexible layout options...",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "66",
        slug: "tanjong-pagar-shophouse",
        title: "Tanjong Pagar – 3-Storey Conservation Shophouse | F&B Approved | $5.2M",
        excerpt: "A restored 3-storey shophouse in Tanjong Pagar with F&B approval and strong rental yield potential...",
        image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "67",
        slug: "one-raffles-place-office",
        title: "One Raffles Place – Premium CBD Office | 3,500 sqft | Tower 2",
        excerpt: "A premium office space in the iconic One Raffles Place Tower 2 with harbour views and MRT connectivity...",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "68",
        slug: "marina-one-retail-unit",
        title: "Marina One – Retail Unit in Mixed-Use Development | 1,500 sqft | $3.8M",
        excerpt: "A high-traffic retail unit in Marina One's bustling ground floor, surrounded by Grade A offices and residences...",
        image: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "69",
        slug: "jurong-innovation-district-b1",
        title: "Jurong Innovation District – B1 Industrial Unit | 5,000 sqft | $1.8M",
        excerpt: "A brand new B1 industrial unit in Jurong Innovation District, perfect for tech startups and R&D companies...",
        image: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "70",
        slug: "arab-street-shophouse",
        title: "Arab Street – Heritage Shophouse with Rooftop Bar Potential | $4.5M",
        excerpt: "A beautifully preserved shophouse in the vibrant Kampong Glam district with rooftop entertainment potential...",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        category: "Commercial",
        readTime: "5 mins read",
    },
    {
        id: "71",
        slug: "mapletree-business-city-office",
        title: "Mapletree Business City – Office Unit with Park View | 2,200 sqft",
        excerpt: "A green-certified office space in MBC with park views and excellent connectivity to Labrador Park MRT...",
        image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
    {
        id: "72",
        slug: "changi-business-park-unit",
        title: "Changi Business Park – B1 Unit with Airport Proximity | 4,000 sqft",
        excerpt: "A strategic B1 unit in Changi Business Park near the airport, ideal for logistics and aviation-related businesses...",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        category: "Commercial",
        readTime: "4 mins read",
    },
];

export interface WebinarItem {
    id: string;
    slug: string;
    title: string;
    thumbnail: string;
    duration: string;
    category: "Most Viewed" | "Latest" | "Editor's Pick";
}

export const webinars: WebinarItem[] = [
    {
        id: "1",
        slug: "germany-digital-infrastructure",
        title: "Germany Implements Comprehensive Digital Infrastructur...",
        thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
        duration: "45:20",
        category: "Most Viewed",
    },
    {
        id: "2",
        slug: "singapore-reit-masterclass",
        title: "Singapore REIT Masterclass: Building a Dividend Portfolio",
        thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
        duration: "58:30",
        category: "Most Viewed",
    },
    {
        id: "3",
        slug: "property-investment-strategies-2026",
        title: "Property Investment Strategies for 2026: Expert Panel Discussion",
        thumbnail: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=600&q=80",
        duration: "1:02:15",
        category: "Most Viewed",
    },
    {
        id: "4",
        slug: "smart-home-tech-future",
        title: "The Future of Smart Home Technology in Singapore Real Estate",
        thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
        duration: "42:10",
        category: "Most Viewed",
    },
    {
        id: "5",
        slug: "hdb-resale-market-deep-dive",
        title: "HDB Resale Market Deep Dive: Trends, Pricing, and Opportunities",
        thumbnail: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&q=80",
        duration: "55:45",
        category: "Latest",
    },
    {
        id: "6",
        slug: "green-building-certification-workshop",
        title: "Green Building Certification Workshop: BCA Green Mark Explained",
        thumbnail: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=600&q=80",
        duration: "1:15:00",
        category: "Latest",
    },
    {
        id: "7",
        slug: "luxury-market-outlook-2026",
        title: "Luxury Market Outlook 2026: Where Are Ultra-High-Net-Worth Buyers Heading?",
        thumbnail: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
        duration: "48:30",
        category: "Latest",
    },
    {
        id: "8",
        slug: "proptech-innovation-summit",
        title: "PropTech Innovation Summit: AI, Blockchain and the Future of Real Estate",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
        duration: "1:05:20",
        category: "Editor's Pick",
    },
    {
        id: "9",
        slug: "landed-property-buying-guide",
        title: "Landed Property Buying Guide: What Every Buyer Must Know",
        thumbnail: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        duration: "52:00",
        category: "Editor's Pick",
    },
    {
        id: "10",
        slug: "cross-border-property-investment",
        title: "Cross-Border Property Investment: Singapore Investors Look Abroad",
        thumbnail: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=600&q=80",
        duration: "47:15",
        category: "Editor's Pick",
    },
];

export const statsData = {
    price: "$1,620,000",
    label: "Average Transaction Price",
    subtitle: "Singapore Private Property Market — Q1 2026",
    change: "+4.2%",
    period: "vs Q4 2025",
};
